/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/frame-compat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frame Compat */
        get: operations["frame_compat_api_frame_compat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screenshot */
        get: operations["screenshot_api_screenshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Async handoff for `POST /api/analyze`.
         *
         *     Returns `AnalyzeResponse` on the success path. On SSRF-guard failure,
         *     advisory-lock contention, or a post-commit enqueue failure, returns a
         *     `JSONResponse` whose body shape is `{error_code, message}` and whose
         *     status mirrors the failure category (400, 503, 500 respectively). We
         *     return a response object (rather than raising HTTPException) so the
         *     body has a stable top-level `error_code` slug — `{"detail": ...}`
         *     would force the client to string-match.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll an async vibecheck job
         * @description Read-only polling endpoint.
         *
         *     Returns the current `JobState` including the `sections` dict (per-slot
         *     progress), `sidebar_payload` once terminal, and a `next_poll_ms` hint.
         *     404 when `job_id` is not found. Rate-limited to
         *     `RATE_LIMIT_POLL_BURST` req/s + `RATE_LIMIT_POLL_SUSTAINED` req/min
         *     per `(ip, job_id)` tuple — exceeding either returns 429 with a
         *     `Retry-After` header.
         */
        get: operations["poll_api_analyze__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/{job_id}/retry/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Section
         * @description Retry one failed slot of a terminal job.
         *
         *     Gate order (strict — each step assumes the prior one passed):
         *       1. Job must exist (404 otherwise).
         *       2. Utterances must have been extracted (409 otherwise — retry is
         *          meaningless if extraction itself failed; the user should resubmit).
         *       3. Job status must be terminal (`done`/`failed`) — running phases
         *          get 409 `cannot_retry_while_running`.
         *       4. The requested slot must exist and be in `failed` state.
         *       5. CAS on the slot's prior attempt_id; a concurrent click loses
         *          with 409 `concurrent_retry_already_claimed`.
         *       6. Post-CAS enqueue. On failure revert the slot to `failed` and
         *          flip the job back to `failed/internal` — the user sees a stable
         *          error card instead of a phantom `analyzing` state.
         */
        post: operations["retry_section_api_analyze__job_id__retry__slug__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_internal/jobs/{job_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Drive one Cloud Tasks delivery through the orchestrator.
         *
         *     The path's `job_id` and the body's `job_id` must agree — Cloud Tasks
         *     signs the URL as well as the body, so a drift here signals either
         *     misconfig or tampering; we reject with 400 rather than trust one side.
         *
         *     Orchestrator return values map to HTTP status:
         *         200: success / stale claim / terminal-failure (no Cloud Tasks retry)
         *         503: transient failure (Cloud Tasks retries per queue config)
         *
         *     Response body is intentionally minimal — Cloud Tasks ignores it.
         */
        post: operations["run__internal_jobs__job_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_internal/jobs/{job_id}/sections/{slug}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Section
         * @description Drive one section-retry Cloud Tasks delivery.
         *
         *     OIDC verification runs at the router-level dependency so a reject
         *     happens before this handler sees the request. On entry we validate
         *     that the path parameters match the body (Cloud Tasks signs both — a
         *     mismatch is either tampering or misconfig; we refuse), then hand off
         *     to `run_section_retry` which owns the CAS-claim → analyze →
         *     mark-done/failed → maybe-finalize sequence.
         *
         *     Status codes mirror the main worker: 200 on success / stale / terminal,
         *     503 on transient failure (Cloud Tasks retries per queue config).
         */
        post: operations["run_section__internal_jobs__job_id__sections__slug__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_internal/_schema_anchor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schema anchor (placeholder, removed in TASK-1473.14)
         * @description Forces JobState into the OpenAPI schema until the real GET /api/analyze/{job_id} endpoint lands. Always returns 410 Gone.
         */
        get: operations["schema_anchor_api__internal__schema_anchor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Url
             * @description HTTP(S) URL of the page to analyze
             */
            url: string;
        };
        /**
         * AnalyzeResponse
         * @description 202 handoff payload.
         *
         *     The response shape is intentionally minimal: the client uses `job_id` to
         *     poll `GET /api/analyze/{job_id}` (TASK-1473.14) for progressive fill.
         *     `cached=true` signals that the pipeline was skipped because a fresh
         *     `vibecheck_analyses` row was already available — the polled job will
         *     reach `status=done` immediately.
         */
        AnalyzeResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** Cached */
            cached: boolean;
        };
        /**
         * ClaimsReport
         * @description Output of `dedupe_claims` — prevalence stats for the Facts sidebar.
         */
        ClaimsReport: {
            /** Deduped Claims */
            deduped_claims: components["schemas"]["DedupedClaim"][];
            /** Total Claims */
            total_claims: number;
            /** Total Unique */
            total_unique: number;
        };
        /**
         * DedupedClaim
         * @description A cluster of semantically-equivalent claims across utterances.
         */
        DedupedClaim: {
            /** Canonical Text */
            canonical_text: string;
            /** Occurrence Count */
            occurrence_count: number;
            /** Author Count */
            author_count: number;
            /** Utterance Ids */
            utterance_ids: string[];
            /** Representative Authors */
            representative_authors: string[];
        };
        /**
         * ErrorCode
         * @description Stable error codes the frontend branches on for inline copy + retry UX.
         * @enum {string}
         */
        ErrorCode: "invalid_url" | "unsafe_url" | "unsupported_site" | "upstream_error" | "extraction_failed" | "timeout" | "rate_limited" | "internal";
        /**
         * FactCheckMatch
         * @description A single fact-check article surfaced by the Google Fact Check Tools API.
         *
         *     One claim (as extracted+deduped from an utterance) can map to multiple
         *     `FactCheckMatch` rows — each corresponding to one `claimReview` entry
         *     returned by the API. We keep the original claim text alongside the
         *     reviewer-supplied metadata so the UI can show provenance clearly.
         */
        FactCheckMatch: {
            /** Claim Text */
            claim_text: string;
            /** Publisher */
            publisher: string;
            /** Review Title */
            review_title: string;
            /** Review Url */
            review_url: string;
            /** Textual Rating */
            textual_rating: string;
            /** Review Date */
            review_date?: string | null;
        };
        /**
         * FactsClaimsSection
         * @description Deduped verifiable claims and any matching published fact-checks.
         */
        FactsClaimsSection: {
            claims_report: components["schemas"]["ClaimsReport"];
            /** Known Misinformation */
            known_misinformation?: components["schemas"]["FactCheckMatch"][];
        };
        /**
         * FlashpointMatch
         * @description Match result from flashpoint detection for a single utterance.
         *
         *     Port of ``ConversationFlashpointMatch`` from opennotes-server, adapted
         *     for the vibecheck utterance model: ``utterance_id`` replaces Discord
         *     ``message_id``; other fields are unchanged.
         */
        FlashpointMatch: {
            /**
             * Scan Type
             * @default conversation_flashpoint
             * @constant
             */
            scan_type: "conversation_flashpoint";
            /**
             * Utterance Id
             * @description Platform-agnostic identifier of the scored utterance
             */
            utterance_id: string;
            /**
             * Derailment Score
             * @description Derailment risk score (0-100)
             */
            derailment_score: number;
            /** @description Categorical risk assessment level */
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Reasoning
             * @description Explanation of detected escalation signals
             */
            reasoning: string;
            /**
             * Context Messages
             * @description Number of context messages analyzed
             */
            context_messages: number;
        };
        /**
         * FrameFinding
         * @description SafeSearch scores for a single video frame.
         */
        FrameFinding: {
            /** Frame Offset Ms */
            frame_offset_ms: number;
            /** Adult */
            adult: number;
            /** Violence */
            violence: number;
            /** Racy */
            racy: number;
            /** Medical */
            medical: number;
            /** Spoof */
            spoof: number;
            /** Flagged */
            flagged: boolean;
            /** Max Likelihood */
            max_likelihood: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HarmfulContentMatch
         * @description A single flagged utterance from a content moderation API.
         */
        HarmfulContentMatch: {
            /** Utterance Id */
            utterance_id: string;
            /** Utterance Text */
            utterance_text: string;
            /** Max Score */
            max_score: number;
            /** Categories */
            categories: {
                [key: string]: boolean;
            };
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Flagged Categories */
            flagged_categories?: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "openai" | "gcp";
        };
        /**
         * ImageModerationMatch
         * @description GCP Vision SafeSearch result for a single image.
         */
        ImageModerationMatch: {
            /** Utterance Id */
            utterance_id: string;
            /** Image Url */
            image_url: string;
            /** Adult */
            adult: number;
            /** Violence */
            violence: number;
            /** Racy */
            racy: number;
            /** Medical */
            medical: number;
            /** Spoof */
            spoof: number;
            /** Flagged */
            flagged: boolean;
            /** Max Likelihood */
            max_likelihood: number;
        };
        /**
         * ImageModerationSection
         * @description GCP Vision SafeSearch results for images referenced in the page.
         */
        ImageModerationSection: {
            /** Matches */
            matches?: components["schemas"]["ImageModerationMatch"][];
        };
        /**
         * JobState
         * @description GET /api/analyze/{job_id} response shape (wired in TASK-1473.14).
         *
         *     Combines job-level lifecycle (status/error_code/error_message), per-slot
         *     progress (sections), the assembled sidebar (sidebar_payload, populated
         *     once all slots finish), and an adaptive polling hint (next_poll_ms) so
         *     clients can back off as the job completes.
         */
        JobState: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Url */
            url: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            error_code?: components["schemas"]["ErrorCode"] | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Error Host
             * @description When ErrorCode.UNSUPPORTED_SITE is returned, the host that triggered the rejection.
             */
            error_host?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["SectionSlot"];
            };
            sidebar_payload?: components["schemas"]["SidebarPayload"] | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Next Poll Ms
             * @description Server-suggested delay until the client should re-poll. Clients use this to implement adaptive cadence (typically 500ms early, 1500ms+ near completion).
             * @default 1500
             */
            next_poll_ms: number;
            /**
             * Page Title
             * @description Extracted page title, sourced from vibecheck_job_utterances. Null until the extractor runs.
             */
            page_title?: string | null;
            /** @description Extracted page shape, sourced from vibecheck_job_utterances. Null until the extractor runs. */
            page_kind?: components["schemas"]["PageKind"] | null;
            /**
             * Utterance Count
             * @description Number of utterances extracted for this job. 0 until the extractor writes any rows.
             * @default 0
             */
            utterance_count: number;
        };
        /**
         * JobStatus
         * @description Lifecycle of a vibecheck job from POST to terminal state.
         * @enum {string}
         */
        JobStatus: "pending" | "extracting" | "analyzing" | "done" | "failed";
        /** OpinionsReport */
        OpinionsReport: {
            sentiment_stats: components["schemas"]["SentimentStatsReport"];
            /** Subjective Claims */
            subjective_claims: components["schemas"]["SubjectiveClaim"][];
        };
        /**
         * OpinionsSection
         * @description Sentiment distribution and extracted subjective claims.
         */
        OpinionsSection: {
            opinions_report: components["schemas"]["OpinionsReport"];
        };
        /**
         * PageKind
         * @description Shape of the source page the extractor handled.
         *
         *     The extractor in TASK-1473.10 picks one of these; downstream rendering
         *     and analysis logic branches on the value (e.g., hierarchical_thread
         *     enables tree-aware flashpoint context).
         * @enum {string}
         */
        PageKind: "blog_post" | "forum_thread" | "hierarchical_thread" | "blog_index" | "article" | "other";
        /**
         * RetryResponse
         * @description 202 handoff payload for a successful retry CAS.
         */
        RetryResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            slug: components["schemas"]["SectionSlug"];
            /**
             * Slot Attempt Id
             * Format: uuid
             */
            slot_attempt_id: string;
        };
        /**
         * RiskLevel
         * @description Categorical risk level for conversation flashpoint detection.
         * @enum {string}
         */
        RiskLevel: "Low Risk" | "Guarded" | "Heated" | "Hostile" | "Dangerous";
        /**
         * RunJobBody
         * @description Cloud Tasks request payload for the run endpoint.
         */
        RunJobBody: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Expected Attempt Id
             * Format: uuid
             */
            expected_attempt_id: string;
        };
        /**
         * RunSectionBody
         * @description Cloud Tasks request payload for the per-section retry endpoint.
         */
        RunSectionBody: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            slug: components["schemas"]["SectionSlug"];
            /**
             * Expected Slot Attempt Id
             * Format: uuid
             */
            expected_slot_attempt_id: string;
        };
        /**
         * SCDReport
         * @description Structured output of `analyze_scd`.
         *
         *     Mirrors the structural intent of Cornell ConvoKit's SCD trajectory summary,
         *     but in a conversational register: a free-form `narrative` describing how
         *     the conversation unfolds, and a structured `speaker_arcs` list ready for
         *     timeline visualization. Legacy fields (`summary`, `tone_labels`,
         *     `per_speaker_notes`, `insufficient_conversation`) are retained so existing
         *     consumers continue to work while orchestrator slot wiring is migrated.
         *     For inputs that lack a real multi-speaker conversation, the model is
         *     bypassed and `insufficient_conversation=True` is set.
         */
        SCDReport: {
            /**
             * Narrative
             * @description Conversational-register narrative (~80-150 words) describing how the conversation unfolds: turn-taking dynamics, escalation or de-escalation, shifts in stance, and persuasive moves. Prose voice — does not restate specific topics, claims, or quotes.
             * @default
             */
            narrative: string;
            /**
             * Speaker Arcs
             * @description Per-speaker arcs across the conversation, ordered for timeline visualization. Each arc carries the speaker label, a short note on their evolution, and an optional utterance index range so the frontend can align the arc with the rendered transcript.
             */
            speaker_arcs?: components["schemas"]["SpeakerArc"][];
            /**
             * Summary
             * @description Legacy: overall conversational-dynamics narrative (<= ~80 words). Captures sentiment shifts, intentions, and persuasive strategies without restating specific topics or claims. Preserved for back-compat with existing consumers; new code should read `narrative` instead.
             */
            summary: string;
            /**
             * Tone Labels
             * @description Legacy: short tone descriptors for the conversation as a whole (e.g. 'combative', 'collaborative', 'dismissive', 'civil'). Preserved for back-compat.
             */
            tone_labels?: string[];
            /**
             * Per Speaker Notes
             * @description Legacy: map of speaker label -> 1-2 sentence observation about that speaker's tone, intent, or conversational strategy. Preserved for back-compat; new code should read `speaker_arcs` for timeline-viz-ready per-speaker information.
             */
            per_speaker_notes?: {
                [key: string]: string;
            };
            /**
             * Insufficient Conversation
             * @description True when the input lacks a real multi-speaker exchange (e.g. a blog post with no comments). When true, callers should treat `summary` as a fixed placeholder and ignore `tone_labels` / `per_speaker_notes` / `speaker_arcs`.
             * @default false
             */
            insufficient_conversation: boolean;
        };
        /**
         * SafetySection
         * @description Harmful-content matches surfaced by OpenAI moderation.
         */
        SafetySection: {
            /** Harmful Content Matches */
            harmful_content_matches?: components["schemas"]["HarmfulContentMatch"][];
        };
        /**
         * SectionSlot
         * @description One sidebar slot's state inside a JobState.
         *
         *     `attempt_id` is regenerated on each retry; Cloud Tasks redeliveries that
         *     carry a stale attempt_id are rejected by the worker. `data` holds the
         *     section-specific payload once `state == DONE` (shape varies by slug).
         */
        SectionSlot: {
            state: components["schemas"]["SectionState"];
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * SectionSlug
         * @description The sidebar slots the async pipeline fills independently.
         * @enum {string}
         */
        SectionSlug: "safety__moderation" | "safety__web_risk" | "safety__image_moderation" | "safety__video_moderation" | "tone_dynamics__flashpoint" | "tone_dynamics__scd" | "facts_claims__dedup" | "facts_claims__known_misinfo" | "opinions_sentiments__sentiment" | "opinions_sentiments__subjective";
        /**
         * SectionState
         * @description Lifecycle of a single sidebar slot during a job.
         * @enum {string}
         */
        SectionState: "pending" | "running" | "done" | "failed";
        /** SentimentScore */
        SentimentScore: {
            /** Utterance Id */
            utterance_id: string;
            /**
             * Label
             * @enum {string}
             */
            label: "positive" | "negative" | "neutral";
            /** Valence */
            valence: number;
        };
        /** SentimentStatsReport */
        SentimentStatsReport: {
            /** Per Utterance */
            per_utterance: components["schemas"]["SentimentScore"][];
            /** Positive Pct */
            positive_pct: number;
            /** Negative Pct */
            negative_pct: number;
            /** Neutral Pct */
            neutral_pct: number;
            /** Mean Valence */
            mean_valence: number;
        };
        /**
         * SidebarPayload
         * @description Top-level response for `POST /api/analyze`.
         *
         *     Aggregates all four sidebar sections plus identity/metadata fields the
         *     frontend needs to render the result. `cached=True` indicates the payload
         *     was served from the Supabase cache (72h TTL) instead of a freshly run
         *     pipeline.
         */
        SidebarPayload: {
            /** Source Url */
            source_url: string;
            /** Page Title */
            page_title?: string | null;
            /** @default other */
            page_kind: components["schemas"]["PageKind"];
            /**
             * Scraped At
             * Format: date-time
             */
            scraped_at: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Cached At */
            cached_at?: string | null;
            safety: components["schemas"]["SafetySection"];
            tone_dynamics: components["schemas"]["ToneDynamicsSection"];
            facts_claims: components["schemas"]["FactsClaimsSection"];
            opinions_sentiments: components["schemas"]["OpinionsSection"];
            web_risk?: components["schemas"]["WebRiskSection"];
            image_moderation?: components["schemas"]["ImageModerationSection"];
            video_moderation?: components["schemas"]["VideoModerationSection"];
        };
        /**
         * SpeakerArc
         * @description Per-speaker arc within a conversation, intended for timeline visualization.
         *
         *     Each arc localizes one speaker's contribution to the conversational shape:
         *     a short prose `note` paired with an optional `utterance_id_range` so the
         *     frontend can map the arc back onto the rendered transcript timeline. The
         *     range is `None` when the LLM cannot confidently localize the arc to a
         *     contiguous span (e.g. interleaved or sparse contributions).
         */
        SpeakerArc: {
            /**
             * Speaker
             * @description Speaker label as it appears in the formatted transcript (e.g. 'alice', 'Speaker1').
             */
            speaker: string;
            /**
             * Note
             * @description 1-2 sentence observation about this speaker's arc: how their tone, intent, or stance evolves across the conversation.
             */
            note: string;
            /**
             * Utterance Id Range
             * @description Inclusive [start, end] 1-indexed utterance index range that this arc covers, for timeline-viz alignment. Exactly two integers with start <= end and start >= 1. `None` when the LLM cannot localize the arc to a contiguous span. Modeled as a list (not a tuple) so the generated OpenAPI schema produces a plain integer array rather than a fixed-length prefixItems tuple, which openapi-fetch widens to `number[]` and would otherwise cause a TS2719 mismatch with the named JobState response type.
             */
            utterance_id_range?: number[] | null;
        };
        /** SubjectiveClaim */
        SubjectiveClaim: {
            /** Claim Text */
            claim_text: string;
            /** Utterance Id */
            utterance_id: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "supports" | "opposes" | "evaluates";
        };
        /**
         * ToneDynamicsSection
         * @description Speaker conversational dynamics + per-utterance flashpoint matches.
         */
        ToneDynamicsSection: {
            scd: components["schemas"]["SCDReport"];
            /** Flashpoint Matches */
            flashpoint_matches?: components["schemas"]["FlashpointMatch"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoModerationMatch
         * @description GCP Video Intelligence SafeSearch result for a single video.
         */
        VideoModerationMatch: {
            /** Utterance Id */
            utterance_id: string;
            /** Video Url */
            video_url: string;
            /** Frame Findings */
            frame_findings: components["schemas"]["FrameFinding"][];
            /** Flagged */
            flagged: boolean;
            /** Max Likelihood */
            max_likelihood: number;
        };
        /**
         * VideoModerationSection
         * @description GCP Video Intelligence SafeSearch results for videos referenced in the page.
         */
        VideoModerationSection: {
            /** Matches */
            matches?: components["schemas"]["VideoModerationMatch"][];
        };
        /**
         * WebRiskFinding
         * @description A URL flagged by GCP Web Risk.
         */
        WebRiskFinding: {
            /** Url */
            url: string;
            /** Threat Types */
            threat_types: ("MALWARE" | "SOCIAL_ENGINEERING" | "UNWANTED_SOFTWARE" | "POTENTIALLY_HARMFUL_APPLICATION")[];
        };
        /**
         * WebRiskSection
         * @description GCP Web Risk findings for URLs referenced in the page.
         */
        WebRiskSection: {
            /** Findings */
            findings?: components["schemas"]["WebRiskFinding"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    frame_compat_api_frame_compat_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenshot_api_screenshot_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_api_analyze__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_section_api_analyze__job_id__retry__slug__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                slug: components["schemas"]["SectionSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run__internal_jobs__job_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunJobBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_section__internal_jobs__job_id__sections__slug__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                slug: components["schemas"]["SectionSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunSectionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schema_anchor_api__internal__schema_anchor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Always — this route is a placeholder so openapi-typescript emits matching JobState/SectionSlot/SectionSlug/etc. type aliases. TASK-1473.14 replaces it with the real polling endpoint. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health__healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
