/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/frame-compat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frame Compat */
        get: operations["frame_compat_api_frame_compat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screenshot */
        get: operations["screenshot_api_screenshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Url
             * @description HTTP(S) URL of the page to analyze
             */
            url: string;
        };
        /**
         * ClaimsReport
         * @description Output of `dedupe_claims` — prevalence stats for the Facts sidebar.
         */
        ClaimsReport: {
            /** Deduped Claims */
            deduped_claims: components["schemas"]["DedupedClaim"][];
            /** Total Claims */
            total_claims: number;
            /** Total Unique */
            total_unique: number;
        };
        /**
         * DedupedClaim
         * @description A cluster of semantically-equivalent claims across utterances.
         */
        DedupedClaim: {
            /** Canonical Text */
            canonical_text: string;
            /** Occurrence Count */
            occurrence_count: number;
            /** Author Count */
            author_count: number;
            /** Utterance Ids */
            utterance_ids: string[];
            /** Representative Authors */
            representative_authors: string[];
        };
        /**
         * FactCheckMatch
         * @description A single fact-check article surfaced by the Google Fact Check Tools API.
         *
         *     One claim (as extracted+deduped from an utterance) can map to multiple
         *     `FactCheckMatch` rows — each corresponding to one `claimReview` entry
         *     returned by the API. We keep the original claim text alongside the
         *     reviewer-supplied metadata so the UI can show provenance clearly.
         */
        FactCheckMatch: {
            /** Claim Text */
            claim_text: string;
            /** Publisher */
            publisher: string;
            /** Review Title */
            review_title: string;
            /** Review Url */
            review_url: string;
            /** Textual Rating */
            textual_rating: string;
            /** Review Date */
            review_date?: string | null;
        };
        /**
         * FactsClaimsSection
         * @description Deduped verifiable claims and any matching published fact-checks.
         */
        FactsClaimsSection: {
            claims_report: components["schemas"]["ClaimsReport"];
            /** Known Misinformation */
            known_misinformation?: components["schemas"]["FactCheckMatch"][];
        };
        /**
         * FlashpointMatch
         * @description Match result from flashpoint detection for a single utterance.
         *
         *     Port of ``ConversationFlashpointMatch`` from opennotes-server, adapted
         *     for the vibecheck utterance model: ``utterance_id`` replaces Discord
         *     ``message_id``; other fields are unchanged.
         */
        FlashpointMatch: {
            /**
             * Scan Type
             * @default conversation_flashpoint
             * @constant
             */
            scan_type: "conversation_flashpoint";
            /**
             * Utterance Id
             * @description Platform-agnostic identifier of the scored utterance
             */
            utterance_id: string;
            /**
             * Derailment Score
             * @description Derailment risk score (0-100)
             */
            derailment_score: number;
            /** @description Categorical risk assessment level */
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Reasoning
             * @description Explanation of detected escalation signals
             */
            reasoning: string;
            /**
             * Context Messages
             * @description Number of context messages analyzed
             */
            context_messages: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HarmfulContentMatch
         * @description A single flagged utterance from the OpenAI moderation API.
         */
        HarmfulContentMatch: {
            /** Utterance Id */
            utterance_id: string;
            /** Max Score */
            max_score: number;
            /** Categories */
            categories: {
                [key: string]: boolean;
            };
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Flagged Categories */
            flagged_categories?: string[];
        };
        /** OpinionsReport */
        OpinionsReport: {
            sentiment_stats: components["schemas"]["SentimentStatsReport"];
            /** Subjective Claims */
            subjective_claims: components["schemas"]["SubjectiveClaim"][];
        };
        /**
         * OpinionsSection
         * @description Sentiment distribution and extracted subjective claims.
         */
        OpinionsSection: {
            opinions_report: components["schemas"]["OpinionsReport"];
        };
        /**
         * RiskLevel
         * @description Categorical risk level for conversation flashpoint detection.
         * @enum {string}
         */
        RiskLevel: "Low Risk" | "Guarded" | "Heated" | "Hostile" | "Dangerous";
        /**
         * SCDReport
         * @description Structured output of `analyze_scd`.
         *
         *     Mirrors the structural intent of Cornell ConvoKit's SCD trajectory summary:
         *     a short dynamics narrative, a small set of tone labels, and per-speaker
         *     observations. For inputs that lack a real multi-speaker conversation, the
         *     model is bypassed and `insufficient_conversation=True` is set.
         */
        SCDReport: {
            /**
             * Summary
             * @description Overall conversational-dynamics narrative (<= ~80 words). Captures sentiment shifts, intentions, and persuasive strategies without restating specific topics or claims.
             */
            summary: string;
            /**
             * Tone Labels
             * @description Short tone descriptors for the conversation as a whole (e.g. 'combative', 'collaborative', 'dismissive', 'civil').
             */
            tone_labels?: string[];
            /**
             * Per Speaker Notes
             * @description Map of speaker label -> 1-2 sentence observation about that speaker's tone, intent, or conversational strategy.
             */
            per_speaker_notes?: {
                [key: string]: string;
            };
            /**
             * Insufficient Conversation
             * @description True when the input lacks a real multi-speaker exchange (e.g. a blog post with no comments). When true, callers should treat `summary` as a fixed placeholder and ignore `tone_labels` / `per_speaker_notes`.
             * @default false
             */
            insufficient_conversation: boolean;
        };
        /**
         * SafetySection
         * @description Harmful-content matches surfaced by OpenAI moderation.
         */
        SafetySection: {
            /** Harmful Content Matches */
            harmful_content_matches?: components["schemas"]["HarmfulContentMatch"][];
        };
        /** SentimentScore */
        SentimentScore: {
            /** Utterance Id */
            utterance_id: string;
            /**
             * Label
             * @enum {string}
             */
            label: "positive" | "negative" | "neutral";
            /** Valence */
            valence: number;
        };
        /** SentimentStatsReport */
        SentimentStatsReport: {
            /** Per Utterance */
            per_utterance: components["schemas"]["SentimentScore"][];
            /** Positive Pct */
            positive_pct: number;
            /** Negative Pct */
            negative_pct: number;
            /** Neutral Pct */
            neutral_pct: number;
            /** Mean Valence */
            mean_valence: number;
        };
        /**
         * SidebarPayload
         * @description Top-level response for `POST /api/analyze`.
         *
         *     Aggregates all four sidebar sections plus identity/metadata fields the
         *     frontend needs to render the result. `cached=True` indicates the payload
         *     was served from the Supabase cache (72h TTL) instead of a freshly run
         *     pipeline.
         */
        SidebarPayload: {
            /** Source Url */
            source_url: string;
            /** Page Title */
            page_title?: string | null;
            /**
             * Page Kind
             * @default other
             * @enum {string}
             */
            page_kind: "blog_post" | "forum_thread" | "article" | "other";
            /**
             * Scraped At
             * Format: date-time
             */
            scraped_at: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            safety: components["schemas"]["SafetySection"];
            tone_dynamics: components["schemas"]["ToneDynamicsSection"];
            facts_claims: components["schemas"]["FactsClaimsSection"];
            opinions_sentiments: components["schemas"]["OpinionsSection"];
        };
        /** SubjectiveClaim */
        SubjectiveClaim: {
            /** Claim Text */
            claim_text: string;
            /** Utterance Id */
            utterance_id: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "supports" | "opposes" | "evaluates";
        };
        /**
         * ToneDynamicsSection
         * @description Speaker conversational dynamics + per-utterance flashpoint matches.
         */
        ToneDynamicsSection: {
            scd: components["schemas"]["SCDReport"];
            /** Flashpoint Matches */
            flashpoint_matches?: components["schemas"]["FlashpointMatch"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    frame_compat_api_frame_compat_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screenshot_api_screenshot_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidebarPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
