"""task-1238: add is_public to simulation_runs

Revision ID: 03f349b8269f
Revises: cc4f90082327
Create Date: 2026-03-06 15:53:32.955133

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03f349b8269f"
down_revision: str | Sequence[str] | None = "cc4f90082327"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_runs",
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index("idx_simulation_runs_is_public", "simulation_runs", ["is_public"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_simulation_runs_is_public", table_name="simulation_runs")
    op.drop_column("simulation_runs", "is_public")
    # ### end Alembic commands ###
