"""add sim_channel_messages table

Revision ID: 0451fbf4ce30
Revises: 1db7b2f41382
Create Date: 2026-03-05 13:43:29.889032

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0451fbf4ce30"
down_revision: str | Sequence[str] | None = "1db7b2f41382"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sim_channel_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("simulation_run_id", sa.UUID(), nullable=False),
        sa.Column("agent_instance_id", sa.UUID(), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"], ["sim_agent_instances.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["simulation_run_id"], ["simulation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sim_channel_messages_run_created",
        "sim_channel_messages",
        ["simulation_run_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sim_channel_messages_agent_instance_id"),
        "sim_channel_messages",
        ["agent_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sim_channel_messages_simulation_run_id"),
        "sim_channel_messages",
        ["simulation_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sim_channel_messages_simulation_run_id"), table_name="sim_channel_messages"
    )
    op.drop_index(
        op.f("ix_sim_channel_messages_agent_instance_id"), table_name="sim_channel_messages"
    )
    op.drop_index("idx_sim_channel_messages_run_created", table_name="sim_channel_messages")
    op.drop_table("sim_channel_messages")
    # ### end Alembic commands ###
