"""Add community_server_id to notes and requests

Revision ID: 04fb5a0487df
Revises: 5809756478d7
Create Date: 2025-11-05 14:08:45.577362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04fb5a0487df"
down_revision: str | Sequence[str] | None = "5809756478d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("community_server_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_notes_community_server_id"), "notes", ["community_server_id"], unique=False
    )
    op.create_foreign_key(
        None, "notes", "community_servers", ["community_server_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("requests", sa.Column("community_server_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_requests_community_server_id"), "requests", ["community_server_id"], unique=False
    )
    op.create_foreign_key(
        None, "requests", "community_servers", ["community_server_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_index(op.f("ix_requests_community_server_id"), table_name="requests")
    op.drop_column("requests", "community_server_id")
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.drop_index(op.f("ix_notes_community_server_id"), table_name="notes")
    op.drop_column("notes", "community_server_id")
    # ### end Alembic commands ###
