"""task-1174: add ai_model column to notes

Revision ID: 0a36caa8cd3b
Revises: 4d7edc118a2e
Create Date: 2026-02-25 12:44:46.000292

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a36caa8cd3b"
down_revision: str | Sequence[str] | None = "4d7edc118a2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("ai_model", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "ai_model")
    # ### end Alembic commands ###
