"""add recent_actions to sim_agent_memory

Revision ID: 0c95d9eab6b7
Revises: f1f5cded5f4a
Create Date: 2026-02-25 17:14:29.721745

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c95d9eab6b7"
down_revision: str | Sequence[str] | None = "f1f5cded5f4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sim_agent_memories",
        sa.Column(
            "recent_actions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sim_agent_memories", "recent_actions")
    # ### end Alembic commands ###
