"""task-1345: add short_description to sim_agents

Revision ID: 0dd89d1cf4df
Revises: 8613f1914eb0
Create Date: 2026-03-16 13:14:44.109677

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd89d1cf4df"
down_revision: str | Sequence[str] | None = "8613f1914eb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opennotes_sim_agents", sa.Column("short_description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opennotes_sim_agents", "short_description")
    # ### end Alembic commands ###
