"""Add AI note generation fields (ai_generated, ai_provider) to notes and fact-check fields to requests

Revision ID: 1b62d2d98e7a
Revises: 750de1eef6cd
Create Date: 2025-11-05 20:58:14.800846

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b62d2d98e7a"
down_revision: str | Sequence[str] | None = "750de1eef6cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes", sa.Column("ai_generated", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("notes", sa.Column("ai_provider", sa.String(length=50), nullable=True))
    op.add_column("requests", sa.Column("priority", sa.String(length=50), nullable=True))
    op.add_column("requests", sa.Column("reason", sa.Text(), nullable=True))
    op.add_column("requests", sa.Column("similarity_score", sa.Float(), nullable=True))
    op.add_column("requests", sa.Column("dataset_name", sa.String(length=100), nullable=True))
    op.add_column("requests", sa.Column("dataset_item_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "dataset_item_id")
    op.drop_column("requests", "dataset_name")
    op.drop_column("requests", "similarity_score")
    op.drop_column("requests", "reason")
    op.drop_column("requests", "priority")
    op.drop_column("notes", "ai_provider")
    op.drop_column("notes", "ai_generated")
    # ### end Alembic commands ###
