"""task-1067.06: add flashpoint_detection_enabled to community_servers

Revision ID: 1ca3f92acb46
Revises: fix_fk_ondelete
Create Date: 2026-02-04 18:43:40.884040

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ca3f92acb46"
down_revision: str | Sequence[str] | None = "fix_fk_ondelete"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "community_servers",
        sa.Column(
            "flashpoint_detection_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("community_servers", "flashpoint_detection_enabled")
    # ### end Alembic commands ###
