"""user_profiles_id_uuidv7_default

Revision ID: 254f9cdd210d
Revises: 2ef4a64dc36e
Create Date: 2026-01-27 17:48:35.343211

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "254f9cdd210d"
down_revision: str | Sequence[str] | None = "2ef4a64dc36e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "community_servers",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuidv7()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuidv7()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "community_servers",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
