"""Sync timestamp defaults for fact_check_items and monitored_channels

Revision ID: 380416c4ea14
Revises: d084f7c9e523
Create Date: 2025-11-04 10:03:02.623799

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "380416c4ea14"
down_revision: str | Sequence[str] | None = "d084f7c9e523"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-04 18:02:48.249485+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-04 18:02:48.249485+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-04 18:02:48.249485+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-04 18:02:48.249485+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
