"""add acted_on_request_ids to sim_agent_memories

Revision ID: 3b17fbc895f3
Revises: b9a4ff797dca
Create Date: 2026-03-19 10:46:15.137859

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b17fbc895f3"
down_revision: str | Sequence[str] | None = "b9a4ff797dca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sim_agent_memories",
        sa.Column(
            "acted_on_request_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sim_agent_memories", "acted_on_request_ids")
    # ### end Alembic commands ###
