"""task-1185: remove community_server_id from sim_agents

Revision ID: 55d3b5d409c0
Revises: 5f64d5620840
Create Date: 2026-02-26 19:39:31.971462

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55d3b5d409c0"
down_revision: str | Sequence[str] | None = "5f64d5620840"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_opennotes_sim_agents_community_server_id"), table_name="opennotes_sim_agents"
    )
    op.drop_constraint(
        op.f("opennotes_sim_agents_community_server_id_fkey"),
        "opennotes_sim_agents",
        type_="foreignkey",
    )
    op.drop_column("opennotes_sim_agents", "community_server_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opennotes_sim_agents",
        sa.Column("community_server_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("opennotes_sim_agents_community_server_id_fkey"),
        "opennotes_sim_agents",
        "community_servers",
        ["community_server_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_opennotes_sim_agents_community_server_id"),
        "opennotes_sim_agents",
        ["community_server_id"],
        unique=False,
    )
    # ### end Alembic commands ###
