"""Add timezone support to autopost datetime fields

Revision ID: 5809756478d7
Revises: b8cc0a81a9ee
Create Date: 2025-11-04 16:53:26.108673

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5809756478d7"
down_revision: str | Sequence[str] | None = "b8cc0a81a9ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auto_posts",
        "posted_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "similarity_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default="0.75",
        existing_nullable=False,
    )
    op.alter_column(
        "server_autopost_config",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server_autopost_config",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "similarity_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0.85'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "auto_posts",
        "posted_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
