"""task-1182: add generation to simulation_runs

Revision ID: 5f64d5620840
Revises: 0c95d9eab6b7
Create Date: 2026-02-26 10:50:02.581434

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f64d5620840"
down_revision: str | Sequence[str] | None = "0c95d9eab6b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_runs", sa.Column("generation", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_runs", "generation")
    # ### end Alembic commands ###
