"""add name to simulation_runs

Revision ID: 63983efd8f6c
Revises: 3b17fbc895f3
Create Date: 2026-03-20 11:07:37.925967

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63983efd8f6c"
down_revision: str | Sequence[str] | None = "3b17fbc895f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulation_runs", sa.Column("name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_runs", "name")
    # ### end Alembic commands ###
