"""Add original_message_content to requests table

Revision ID: 76e7a7cc7edf
Revises: 0b070ededde0
Create Date: 2025-11-18 17:49:09.032629

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76e7a7cc7edf"
down_revision: str | Sequence[str] | None = "0b070ededde0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("original_message_content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "original_message_content")
    # ### end Alembic commands ###
