"""task_575_rename_discord_fields_to_platform_fields_in_message_archive

Revision ID: 78e946dc6f26
Revises: fix_llm_config_tz
Create Date: 2025-11-21 16:25:20.850580

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78e946dc6f26"
down_revision: str | Sequence[str] | None = "fix_llm_config_tz"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_archive", sa.Column("platform_message_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "message_archive", sa.Column("platform_channel_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "message_archive", sa.Column("platform_author_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "message_archive",
        sa.Column("platform_timestamp", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_index(op.f("idx_message_archive_discord_message"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_discord_author_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_discord_channel_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_discord_message_id"), table_name="message_archive")
    op.create_index(
        "idx_message_archive_platform_message",
        "message_archive",
        ["platform_message_id", "platform_channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_archive_platform_author_id"),
        "message_archive",
        ["platform_author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_archive_platform_channel_id"),
        "message_archive",
        ["platform_channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_archive_platform_message_id"),
        "message_archive",
        ["platform_message_id"],
        unique=False,
    )
    op.drop_column("message_archive", "discord_channel_id")
    op.drop_column("message_archive", "discord_author_id")
    op.drop_column("message_archive", "discord_message_id")
    op.drop_column("message_archive", "discord_timestamp")
    op.drop_index(op.f("idx_requests_tweet_status"), table_name="requests")
    op.drop_index(op.f("ix_requests_tweet_id"), table_name="requests")
    op.drop_column("requests", "tweet_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("tweet_id", sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_requests_tweet_id"), "requests", ["tweet_id"], unique=False)
    op.create_index(
        op.f("idx_requests_tweet_status"), "requests", ["tweet_id", "status"], unique=False
    )
    op.add_column(
        "message_archive",
        sa.Column(
            "discord_timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "message_archive",
        sa.Column("discord_message_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "message_archive",
        sa.Column("discord_author_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "message_archive",
        sa.Column("discord_channel_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_message_archive_platform_message_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_platform_channel_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_platform_author_id"), table_name="message_archive")
    op.drop_index("idx_message_archive_platform_message", table_name="message_archive")
    op.create_index(
        op.f("ix_message_archive_discord_message_id"),
        "message_archive",
        ["discord_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_archive_discord_channel_id"),
        "message_archive",
        ["discord_channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_archive_discord_author_id"),
        "message_archive",
        ["discord_author_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_message_archive_discord_message"),
        "message_archive",
        ["discord_message_id", "discord_channel_id"],
        unique=False,
    )
    op.drop_column("message_archive", "platform_timestamp")
    op.drop_column("message_archive", "platform_author_id")
    op.drop_column("message_archive", "platform_channel_id")
    op.drop_column("message_archive", "platform_message_id")
    # ### end Alembic commands ###
