"""resolve_index_and_timestamp_drift

Revision ID: 7bc4295d643c
Revises: dd5369cf2006
Create Date: 2025-11-03 10:57:38.730881

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bc4295d643c"
down_revision: str | Sequence[str] | None = "dd5369cf2006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def drop_index_if_exists(bind, index_name, table_name):
    """Drop index if it exists in the database."""
    inspector = sa.inspect(bind)
    indexes = {idx["name"] for idx in inspector.get_indexes(table_name)}
    if index_name in indexes:
        op.drop_index(index_name, table_name=table_name)


def create_index_if_not_exists(bind, index_name, table_name, columns, unique=False):
    """Create index if it doesn't already exist."""
    inspector = sa.inspect(bind)
    indexes = {idx["name"] for idx in inspector.get_indexes(table_name)}
    if index_name not in indexes:
        op.create_index(index_name, table_name, columns, unique=unique)


def drop_constraint_if_exists(bind, constraint_name, table_name, constraint_type="foreignkey"):
    """Drop constraint if it exists in the database."""
    inspector = sa.inspect(bind)
    fks = {fk["name"] for fk in inspector.get_foreign_keys(table_name)}
    if constraint_name in fks:
        op.drop_constraint(constraint_name, table_name, type_=constraint_type)


def create_foreign_key_if_not_exists(
    bind, fk_name, source_table, target_table, local_cols, remote_cols, **kwargs
):
    """Create foreign key if it doesn't already exist."""
    inspector = sa.inspect(bind)
    fks = {fk["name"] for fk in inspector.get_foreign_keys(source_table)}
    if fk_name not in fks:
        op.create_foreign_key(
            fk_name, source_table, target_table, local_cols, remote_cols, **kwargs
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    drop_index_if_exists(bind, "idx_api_keys_key_prefix_active", "api_keys")
    create_index_if_not_exists(
        bind, "ix_api_keys_key_prefix", "api_keys", ["key_prefix"], unique=False
    )

    drop_index_if_exists(bind, "ix_auto_posts_channel_id", "auto_posts")
    drop_index_if_exists(bind, "ix_auto_posts_guild_id", "auto_posts")
    drop_index_if_exists(bind, "ix_auto_posts_note_id", "auto_posts")
    drop_index_if_exists(bind, "ix_auto_posts_original_message_id", "auto_posts")
    drop_index_if_exists(bind, "ix_auto_posts_posted_at", "auto_posts")
    op.alter_column(
        "community_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "community_members",
        "banned_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "community_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "community_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=True,
    )
    create_index_if_not_exists(
        bind,
        "ix_community_members_community_id",
        "community_members",
        ["community_id"],
        unique=False,
    )
    create_index_if_not_exists(
        bind, "ix_community_members_is_active", "community_members", ["is_active"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_members_is_external", "community_members", ["is_external"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_members_joined_at", "community_members", ["joined_at"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_members_profile_id", "community_members", ["profile_id"], unique=False
    )
    create_index_if_not_exists(
        bind,
        "ix_community_members_reputation_in_community",
        "community_members",
        ["reputation_in_community"],
        unique=False,
    )
    create_index_if_not_exists(
        bind, "ix_community_members_role", "community_members", ["role"], unique=False
    )
    op.alter_column(
        "community_server_llm_config",
        "last_daily_reset",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "community_server_llm_config",
        "last_monthly_reset",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    drop_index_if_exists(bind, "idx_llm_config_community_server_id", "community_server_llm_config")
    drop_index_if_exists(bind, "idx_llm_config_created_at", "community_server_llm_config")
    drop_index_if_exists(bind, "idx_llm_config_id", "community_server_llm_config")
    drop_index_if_exists(bind, "idx_llm_config_provider", "community_server_llm_config")
    create_index_if_not_exists(
        bind,
        "ix_community_server_llm_config_community_server_id",
        "community_server_llm_config",
        ["community_server_id"],
        unique=False,
    )
    create_index_if_not_exists(
        bind,
        "ix_community_server_llm_config_created_at",
        "community_server_llm_config",
        ["created_at"],
        unique=False,
    )
    create_index_if_not_exists(
        bind,
        "ix_community_server_llm_config_enabled",
        "community_server_llm_config",
        ["enabled"],
        unique=False,
    )
    create_index_if_not_exists(
        bind,
        "ix_community_server_llm_config_id",
        "community_server_llm_config",
        ["id"],
        unique=False,
    )
    create_index_if_not_exists(
        bind,
        "ix_community_server_llm_config_provider",
        "community_server_llm_config",
        ["provider"],
        unique=False,
    )
    drop_index_if_exists(bind, "idx_community_servers_created_at", "community_servers")
    drop_index_if_exists(bind, "idx_community_servers_id", "community_servers")
    drop_index_if_exists(bind, "idx_community_servers_platform", "community_servers")
    drop_index_if_exists(bind, "idx_community_servers_platform_id_unique", "community_servers")
    drop_index_if_exists(bind, "idx_community_servers_platform_id", "community_servers")
    create_index_if_not_exists(
        bind,
        "idx_community_servers_platform_id",
        "community_servers",
        ["platform", "platform_id"],
        unique=True,
    )
    create_index_if_not_exists(
        bind, "ix_community_servers_created_at", "community_servers", ["created_at"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_servers_id", "community_servers", ["id"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_servers_is_active", "community_servers", ["is_active"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_servers_is_public", "community_servers", ["is_public"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_servers_platform", "community_servers", ["platform"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_community_servers_platform_id", "community_servers", ["platform_id"], unique=False
    )
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    drop_index_if_exists(bind, "idx_fact_check_items_id", "fact_check_items")
    create_index_if_not_exists(
        bind, "ix_fact_check_items_dataset_name", "fact_check_items", ["dataset_name"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_fact_check_items_dataset_tags", "fact_check_items", ["dataset_tags"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_fact_check_items_id", "fact_check_items", ["id"], unique=False
    )
    drop_index_if_exists(bind, "ix_interactions_guild_id", "interactions")
    create_index_if_not_exists(
        bind,
        "ix_interactions_community_server_id",
        "interactions",
        ["community_server_id"],
        unique=False,
    )
    drop_index_if_exists(bind, "idx_llm_usage_community_server_id", "llm_usage_log")
    drop_index_if_exists(bind, "idx_llm_usage_id", "llm_usage_log")
    drop_index_if_exists(bind, "idx_llm_usage_provider", "llm_usage_log")
    drop_index_if_exists(bind, "idx_llm_usage_timestamp", "llm_usage_log")
    create_index_if_not_exists(
        bind,
        "ix_llm_usage_log_community_server_id",
        "llm_usage_log",
        ["community_server_id"],
        unique=False,
    )
    create_index_if_not_exists(bind, "ix_llm_usage_log_id", "llm_usage_log", ["id"], unique=False)
    create_index_if_not_exists(
        bind, "ix_llm_usage_log_provider", "llm_usage_log", ["provider"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_llm_usage_log_success", "llm_usage_log", ["success"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_llm_usage_log_timestamp", "llm_usage_log", ["timestamp"], unique=False
    )
    drop_index_if_exists(bind, "idx_message_archive_content_type", "message_archive")
    drop_index_if_exists(bind, "idx_message_archive_discord_author_id", "message_archive")
    drop_index_if_exists(bind, "idx_message_archive_discord_channel_id", "message_archive")
    drop_index_if_exists(bind, "idx_message_archive_discord_message_id", "message_archive")
    drop_index_if_exists(bind, "idx_message_archive_created_at", "message_archive")
    create_index_if_not_exists(
        bind, "idx_message_archive_created_at", "message_archive", ["created_at"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_message_archive_content_type", "message_archive", ["content_type"], unique=False
    )
    create_index_if_not_exists(
        bind,
        "ix_message_archive_discord_author_id",
        "message_archive",
        ["discord_author_id"],
        unique=False,
    )
    create_index_if_not_exists(
        bind,
        "ix_message_archive_discord_channel_id",
        "message_archive",
        ["discord_channel_id"],
        unique=False,
    )
    create_index_if_not_exists(
        bind,
        "ix_message_archive_discord_message_id",
        "message_archive",
        ["discord_message_id"],
        unique=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    drop_index_if_exists(bind, "idx_monitored_channels_channel_id", "monitored_channels")
    drop_index_if_exists(bind, "idx_monitored_channels_community_server_id", "monitored_channels")
    drop_index_if_exists(bind, "idx_monitored_channels_id", "monitored_channels")
    create_index_if_not_exists(
        bind, "ix_monitored_channels_channel_id", "monitored_channels", ["channel_id"], unique=False
    )
    create_index_if_not_exists(
        bind,
        "ix_monitored_channels_community_server_id",
        "monitored_channels",
        ["community_server_id"],
        unique=False,
    )
    create_index_if_not_exists(
        bind, "ix_monitored_channels_id", "monitored_channels", ["id"], unique=False
    )
    op.alter_column("notes", "helpfulness_score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "notes",
        "status",
        existing_type=postgresql.ENUM(
            "NEEDS_MORE_RATINGS",
            "CURRENTLY_RATED_HELPFUL",
            "CURRENTLY_RATED_NOT_HELPFUL",
            name="note_status",
        ),
        nullable=False,
    )
    op.alter_column(
        "notes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "notes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    drop_index_if_exists(bind, "idx_notes_channel_id", "notes")
    drop_index_if_exists(bind, "ix_notes_classification_status", "notes")
    drop_index_if_exists(bind, "ix_notes_created_status", "notes")
    drop_index_if_exists(bind, "ix_notes_tweet_status", "notes")
    create_index_if_not_exists(
        bind, "ix_notes_author_profile_id", "notes", ["author_profile_id"], unique=False
    )
    create_index_if_not_exists(bind, "ix_notes_channel_id", "notes", ["channel_id"], unique=False)
    drop_constraint_if_exists(bind, "fk_notes_request_id", "notes", constraint_type="foreignkey")
    create_foreign_key_if_not_exists(
        bind, None, "notes", "requests", ["request_id"], ["request_id"], ondelete="SET NULL"
    )
    op.alter_column(
        "ratings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "ratings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    create_index_if_not_exists(
        bind, "ix_ratings_rater_profile_id", "ratings", ["rater_profile_id"], unique=False
    )
    op.alter_column(
        "requests",
        "migrated_from_content",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    create_index_if_not_exists(
        bind, "ix_requests_message_archive_id", "requests", ["message_archive_id"], unique=False
    )
    drop_constraint_if_exists(
        bind, "requests_note_id_fkey", "requests", constraint_type="foreignkey"
    )
    drop_index_if_exists(bind, "ix_server_autopost_config_channel_id", "server_autopost_config")
    drop_index_if_exists(bind, "ix_server_autopost_config_guild_id", "server_autopost_config")
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "retry_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_identities",
        "credentials",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment='Encrypted provider-specific credential data. Encrypted using Fernet (AES-128 CBC + HMAC). Format: {"encrypted": "base64_ciphertext"}',
        existing_nullable=True,
    )
    op.alter_column(
        "user_identities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_identities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=True,
    )
    drop_index_if_exists(bind, "idx_user_identities_email_verified", "user_identities")
    create_index_if_not_exists(
        bind,
        "ix_user_identities_email_verified",
        "user_identities",
        ["email_verified"],
        unique=False,
    )
    create_index_if_not_exists(
        bind, "ix_user_identities_profile_id", "user_identities", ["profile_id"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_user_identities_provider", "user_identities", ["provider"], unique=False
    )
    create_index_if_not_exists(
        bind,
        "ix_user_identities_provider_user_id",
        "user_identities",
        ["provider_user_id"],
        unique=False,
    )
    op.alter_column(
        "user_profiles",
        "banned_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "user_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        nullable=True,
    )
    drop_index_if_exists(bind, "idx_user_profiles_role", "user_profiles")
    create_index_if_not_exists(
        bind, "ix_user_profiles_display_name", "user_profiles", ["display_name"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_user_profiles_is_active", "user_profiles", ["is_active"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_user_profiles_is_banned", "user_profiles", ["is_banned"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_user_profiles_is_human", "user_profiles", ["is_human"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_user_profiles_reputation", "user_profiles", ["reputation"], unique=False
    )
    create_index_if_not_exists(
        bind, "ix_user_profiles_role", "user_profiles", ["role"], unique=False
    )
    drop_index_if_exists(bind, "ix_webhooks_guild_id", "webhooks")
    create_index_if_not_exists(
        bind, "ix_webhooks_community_server_id", "webhooks", ["community_server_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhooks_community_server_id"), table_name="webhooks")
    op.create_index(op.f("ix_webhooks_guild_id"), "webhooks", ["community_server_id"], unique=False)
    op.drop_index(op.f("ix_user_profiles_role"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_reputation"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_is_human"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_is_banned"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_is_active"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_display_name"), table_name="user_profiles")
    op.create_index(op.f("idx_user_profiles_role"), "user_profiles", ["role"], unique=False)
    op.alter_column(
        "user_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "banned_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_user_identities_provider_user_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_provider"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_profile_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_email_verified"), table_name="user_identities")
    op.create_index(
        op.f("idx_user_identities_email_verified"),
        "user_identities",
        ["email_verified"],
        unique=False,
    )
    op.alter_column(
        "user_identities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "user_identities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_identities",
        "credentials",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='Encrypted provider-specific credential data. Encrypted using Fernet (AES-128 CBC + HMAC). Format: {"encrypted": "base64_ciphertext"}',
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "retry_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_server_autopost_config_guild_id"),
        "server_autopost_config",
        ["community_server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_autopost_config_channel_id"),
        "server_autopost_config",
        ["channel_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("requests_note_id_fkey"), "requests", "notes", ["note_id"], ["note_id"]
    )
    op.drop_index(op.f("ix_requests_message_archive_id"), table_name="requests")
    op.alter_column(
        "requests",
        "migrated_from_content",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_ratings_rater_profile_id"), table_name="ratings")
    op.alter_column(
        "ratings",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=None,
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "ratings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_notes_request_id"), "notes", "requests", ["request_id"], ["request_id"]
    )
    op.drop_index(op.f("ix_notes_channel_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_author_profile_id"), table_name="notes")
    op.create_index(op.f("ix_notes_tweet_status"), "notes", ["tweet_id", "status"], unique=False)
    op.create_index(
        op.f("ix_notes_created_status"), "notes", ["created_at", "status"], unique=False
    )
    op.create_index(
        op.f("ix_notes_classification_status"), "notes", ["classification", "status"], unique=False
    )
    op.create_index(op.f("idx_notes_channel_id"), "notes", ["channel_id"], unique=False)
    op.alter_column(
        "notes",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=None,
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "notes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "notes",
        "status",
        existing_type=postgresql.ENUM(
            "NEEDS_MORE_RATINGS",
            "CURRENTLY_RATED_HELPFUL",
            "CURRENTLY_RATED_NOT_HELPFUL",
            name="note_status",
        ),
        nullable=True,
    )
    op.alter_column("notes", "helpfulness_score", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index(op.f("ix_monitored_channels_id"), table_name="monitored_channels")
    op.drop_index(
        op.f("ix_monitored_channels_community_server_id"), table_name="monitored_channels"
    )
    op.drop_index(op.f("ix_monitored_channels_channel_id"), table_name="monitored_channels")
    op.create_index(op.f("idx_monitored_channels_id"), "monitored_channels", ["id"], unique=False)
    op.create_index(
        op.f("idx_monitored_channels_community_server_id"),
        "monitored_channels",
        ["community_server_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_monitored_channels_channel_id"),
        "monitored_channels",
        ["channel_id"],
        unique=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 18:57:24.21352+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 18:57:24.21352+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_message_archive_discord_message_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_discord_channel_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_discord_author_id"), table_name="message_archive")
    op.drop_index(op.f("ix_message_archive_content_type"), table_name="message_archive")
    op.drop_index("idx_message_archive_created_at", table_name="message_archive")
    op.create_index(
        op.f("idx_message_archive_created_at"),
        "message_archive",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_message_archive_discord_message_id"),
        "message_archive",
        ["discord_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_message_archive_discord_channel_id"),
        "message_archive",
        ["discord_channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_message_archive_discord_author_id"),
        "message_archive",
        ["discord_author_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_message_archive_content_type"), "message_archive", ["content_type"], unique=False
    )
    op.drop_index(op.f("ix_llm_usage_log_timestamp"), table_name="llm_usage_log")
    op.drop_index(op.f("ix_llm_usage_log_success"), table_name="llm_usage_log")
    op.drop_index(op.f("ix_llm_usage_log_provider"), table_name="llm_usage_log")
    op.drop_index(op.f("ix_llm_usage_log_id"), table_name="llm_usage_log")
    op.drop_index(op.f("ix_llm_usage_log_community_server_id"), table_name="llm_usage_log")
    op.create_index(op.f("idx_llm_usage_timestamp"), "llm_usage_log", ["timestamp"], unique=False)
    op.create_index(op.f("idx_llm_usage_provider"), "llm_usage_log", ["provider"], unique=False)
    op.create_index(op.f("idx_llm_usage_id"), "llm_usage_log", ["id"], unique=False)
    op.create_index(
        op.f("idx_llm_usage_community_server_id"),
        "llm_usage_log",
        ["community_server_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_interactions_community_server_id"), table_name="interactions")
    op.create_index(
        op.f("ix_interactions_guild_id"), "interactions", ["community_server_id"], unique=False
    )
    op.drop_index(op.f("ix_fact_check_items_id"), table_name="fact_check_items")
    op.drop_index(op.f("ix_fact_check_items_dataset_tags"), table_name="fact_check_items")
    op.drop_index(op.f("ix_fact_check_items_dataset_name"), table_name="fact_check_items")
    op.create_index(op.f("idx_fact_check_items_id"), "fact_check_items", ["id"], unique=False)
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 18:57:24.21352+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 18:57:24.21352+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_community_servers_platform_id"), table_name="community_servers")
    op.drop_index(op.f("ix_community_servers_platform"), table_name="community_servers")
    op.drop_index(op.f("ix_community_servers_is_public"), table_name="community_servers")
    op.drop_index(op.f("ix_community_servers_is_active"), table_name="community_servers")
    op.drop_index(op.f("ix_community_servers_id"), table_name="community_servers")
    op.drop_index(op.f("ix_community_servers_created_at"), table_name="community_servers")
    op.drop_index("idx_community_servers_platform_id", table_name="community_servers")
    op.create_index(
        op.f("idx_community_servers_platform_id"),
        "community_servers",
        ["platform_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_community_servers_platform_id_unique"),
        "community_servers",
        ["platform", "platform_id"],
        unique=True,
    )
    op.create_index(
        op.f("idx_community_servers_platform"), "community_servers", ["platform"], unique=False
    )
    op.create_index(op.f("idx_community_servers_id"), "community_servers", ["id"], unique=False)
    op.create_index(
        op.f("idx_community_servers_created_at"), "community_servers", ["created_at"], unique=False
    )
    op.drop_index(
        op.f("ix_community_server_llm_config_provider"), table_name="community_server_llm_config"
    )
    op.drop_index(
        op.f("ix_community_server_llm_config_id"), table_name="community_server_llm_config"
    )
    op.drop_index(
        op.f("ix_community_server_llm_config_enabled"), table_name="community_server_llm_config"
    )
    op.drop_index(
        op.f("ix_community_server_llm_config_created_at"), table_name="community_server_llm_config"
    )
    op.drop_index(
        op.f("ix_community_server_llm_config_community_server_id"),
        table_name="community_server_llm_config",
    )
    op.create_index(
        op.f("idx_llm_config_provider"), "community_server_llm_config", ["provider"], unique=False
    )
    op.create_index(op.f("idx_llm_config_id"), "community_server_llm_config", ["id"], unique=False)
    op.create_index(
        op.f("idx_llm_config_created_at"),
        "community_server_llm_config",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_llm_config_community_server_id"),
        "community_server_llm_config",
        ["community_server_id"],
        unique=False,
    )
    op.alter_column(
        "community_server_llm_config",
        "last_monthly_reset",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "community_server_llm_config",
        "last_daily_reset",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_community_members_role"), table_name="community_members")
    op.drop_index(
        op.f("ix_community_members_reputation_in_community"), table_name="community_members"
    )
    op.drop_index(op.f("ix_community_members_profile_id"), table_name="community_members")
    op.drop_index(op.f("ix_community_members_joined_at"), table_name="community_members")
    op.drop_index(op.f("ix_community_members_is_external"), table_name="community_members")
    op.drop_index(op.f("ix_community_members_is_active"), table_name="community_members")
    op.drop_index(op.f("ix_community_members_community_id"), table_name="community_members")
    op.alter_column(
        "community_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "community_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "community_members",
        "banned_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "community_members",
        "joined_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_auto_posts_posted_at"), "auto_posts", ["posted_at"], unique=False)
    op.create_index(
        op.f("ix_auto_posts_original_message_id"),
        "auto_posts",
        ["original_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_auto_posts_note_id"), "auto_posts", ["note_id"], unique=False)
    op.create_index(
        op.f("ix_auto_posts_guild_id"), "auto_posts", ["community_server_id"], unique=False
    )
    op.create_index(op.f("ix_auto_posts_channel_id"), "auto_posts", ["channel_id"], unique=False)
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.create_index(
        op.f("idx_api_keys_key_prefix_active"),
        "api_keys",
        ["key_prefix", "is_active"],
        unique=False,
    )
    # ### end Alembic commands ###
