"""task-1222.13: drop redundant sim_channel_messages simulation_run_id index

Revision ID: 82909ed55243
Revises: c772521f43e9
Create Date: 2026-03-10 16:17:48.075197

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82909ed55243"
down_revision: str | Sequence[str] | None = "c772521f43e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sim_channel_messages_simulation_run_id"), table_name="sim_channel_messages"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sim_channel_messages_simulation_run_id"),
        "sim_channel_messages",
        ["simulation_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###
