"""add scoring_snapshots table

Revision ID: 84eb220a346a
Revises: f591db73272e
Create Date: 2026-03-08 16:40:28.188819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84eb220a346a"
down_revision: str | Sequence[str] | None = "f591db73272e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoring_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("community_server_id", sa.UUID(), nullable=False),
        sa.Column(
            "scored_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "rater_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "note_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("global_intercept", sa.Float(), server_default="0.0", nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["community_server_id"], ["community_servers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_server_id"),
    )
    op.create_index(
        "idx_scoring_snapshots_community_server_id",
        "scoring_snapshots",
        ["community_server_id"],
        unique=True,
    )
    op.create_index(
        "idx_scoring_snapshots_scored_at", "scoring_snapshots", ["scored_at"], unique=False
    )
    op.create_index(op.f("ix_scoring_snapshots_id"), "scoring_snapshots", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scoring_snapshots_id"), table_name="scoring_snapshots")
    op.drop_index("idx_scoring_snapshots_scored_at", table_name="scoring_snapshots")
    op.drop_index("idx_scoring_snapshots_community_server_id", table_name="scoring_snapshots")
    op.drop_table("scoring_snapshots")
    # ### end Alembic commands ###
