"""Update foreign key constraints to RESTRICT for community_server_id

Revision ID: 8510bfaa2741
Revises: 7791f3eca498
Create Date: 2025-11-11 14:34:58.625137

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8510bfaa2741"
down_revision: str | Sequence[str] | None = "7791f3eca498"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("notes_community_server_id_fkey"), "notes", type_="foreignkey")
    op.create_foreign_key(
        None, "notes", "community_servers", ["community_server_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(op.f("requests_community_server_id_fkey"), "requests", type_="foreignkey")
    op.create_foreign_key(
        None, "requests", "community_servers", ["community_server_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("requests_community_server_id_fkey"),
        "requests",
        "community_servers",
        ["community_server_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("notes_community_server_id_fkey"),
        "notes",
        "community_servers",
        ["community_server_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
