"""task-1132: add missing indexes

Revision ID: 88ad7e42c01e
Revises: 8b4c5d6e7f8a
Create Date: 2026-02-21 13:06:07.561418

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88ad7e42c01e"
down_revision: str | Sequence[str] | None = "8b4c5d6e7f8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_sim_agent_instances_state", "sim_agent_instances", ["state"], unique=False)
    op.create_index(
        op.f("ix_sim_agent_memories_agent_instance_id"),
        "sim_agent_memories",
        ["agent_instance_id"],
        unique=False,
    )
    op.create_index("idx_simulation_runs_status", "simulation_runs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_simulation_runs_status", table_name="simulation_runs")
    op.drop_index(op.f("ix_sim_agent_memories_agent_instance_id"), table_name="sim_agent_memories")
    op.drop_index("idx_sim_agent_instances_state", table_name="sim_agent_instances")
    # ### end Alembic commands ###
