"""task-1082: enable flashpoint detection by default

Revision ID: 992453458994
Revises: 1ca3f92acb46
Create Date: 2026-02-06 00:37:15.492758

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "992453458994"
down_revision: str | Sequence[str] | None = "1ca3f92acb46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "UPDATE community_servers SET flashpoint_detection_enabled = true"
        " WHERE flashpoint_detection_enabled = false"
    )
    op.alter_column(
        "community_servers",
        "flashpoint_detection_enabled",
        existing_type=sa.BOOLEAN(),
        server_default="true",
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "community_servers",
        "flashpoint_detection_enabled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
