"""drop_tasks_table_after_task_840_cleanup

Revision ID: 9a0353b49146
Revises: 41e171275262
Create Date: 2025-12-22 15:20:44.076197

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a0353b49146"
down_revision: str | Sequence[str] | None = "41e171275262"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF EXISTS since production database state may differ from local
    # (tasks table and indexes may not exist in production)
    op.execute("DROP INDEX IF EXISTS ix_tasks_created_at")
    op.execute("DROP INDEX IF EXISTS ix_tasks_id")
    op.execute("DROP INDEX IF EXISTS ix_tasks_interaction_id")
    op.execute("DROP INDEX IF EXISTS ix_tasks_status")
    op.execute("DROP INDEX IF EXISTS ix_tasks_task_id")
    op.execute("DROP TABLE IF EXISTS tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("interaction_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("interaction_token", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("application_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("task_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "task_data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "result", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("retry_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("uuidv7()"), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_pkey")),
    )
    op.create_index(op.f("ix_tasks_task_id"), "tasks", ["task_id"], unique=True)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_interaction_id"), "tasks", ["interaction_id"], unique=False)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    # ### end Alembic commands ###
