"""add is_service_account field to users table

Revision ID: 9afd6edf6b4f
Revises: 1b62d2d98e7a
Create Date: 2025-11-06 09:01:24.241489

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9afd6edf6b4f"
down_revision: str | Sequence[str] | None = "1b62d2d98e7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_service_account", sa.Boolean(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_service_account")
    # ### end Alembic commands ###
