"""fix_timestamp_server_defaults_for_fact_check_and_monitored_channels

Revision ID: 9fea737ffdc6
Revises: 7bc4295d643c
Create Date: 2025-11-03 11:34:24.825724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fea737ffdc6"
down_revision: str | Sequence[str] | None = "7bc4295d643c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
