"""task-1203-01: add restart audit tables and columns

Revision ID: a7c54bf2fe15
Revises: 55d3b5d409c0
Create Date: 2026-03-02 15:32:21.801551

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7c54bf2fe15"
down_revision: str | Sequence[str] | None = "55d3b5d409c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sim_agent_run_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("agent_instance_id", sa.UUID(), nullable=False),
        sa.Column("simulation_run_id", sa.UUID(), nullable=False),
        sa.Column("restart_number", sa.Integer(), nullable=False),
        sa.Column("turns_in_segment", sa.Integer(), server_default="0", nullable=False),
        sa.Column("state_at_end", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sim_agent_run_logs_instance_restart",
        "sim_agent_run_logs",
        ["agent_instance_id", "restart_number"],
        unique=False,
    )
    op.create_index(
        "idx_sim_agent_run_logs_run_id", "sim_agent_run_logs", ["simulation_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_sim_agent_run_logs_agent_instance_id"),
        "sim_agent_run_logs",
        ["agent_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sim_agent_run_logs_simulation_run_id"),
        "sim_agent_run_logs",
        ["simulation_run_id"],
        unique=False,
    )
    op.create_table(
        "simulation_run_configs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("simulation_run_id", sa.UUID(), nullable=False),
        sa.Column("restart_number", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_turns_per_agent", sa.Integer(), nullable=False),
        sa.Column("turn_cadence_seconds", sa.Integer(), nullable=False),
        sa.Column("max_agents", sa.Integer(), nullable=False),
        sa.Column("removal_rate", sa.Float(), nullable=False),
        sa.Column("scoring_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_simulation_run_configs_run_restart",
        "simulation_run_configs",
        ["simulation_run_id", "restart_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_run_configs_simulation_run_id"),
        "simulation_run_configs",
        ["simulation_run_id"],
        unique=False,
    )
    op.add_column(
        "sim_agent_instances",
        sa.Column("cumulative_turn_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("sim_agent_instances", sa.Column("current_run_log_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "sim_agent_instances",
        "sim_agent_run_logs",
        ["current_run_log_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "simulation_runs",
        sa.Column("cumulative_turns", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "simulation_runs",
        sa.Column("restart_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("simulation_runs", sa.Column("current_config_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "simulation_runs",
        "simulation_run_configs",
        ["current_config_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "simulation_runs", type_="foreignkey")
    op.drop_column("simulation_runs", "current_config_id")
    op.drop_column("simulation_runs", "restart_count")
    op.drop_column("simulation_runs", "cumulative_turns")
    op.drop_constraint(None, "sim_agent_instances", type_="foreignkey")
    op.drop_column("sim_agent_instances", "current_run_log_id")
    op.drop_column("sim_agent_instances", "cumulative_turn_count")
    op.drop_index(
        op.f("ix_simulation_run_configs_simulation_run_id"), table_name="simulation_run_configs"
    )
    op.drop_index("idx_simulation_run_configs_run_restart", table_name="simulation_run_configs")
    op.drop_table("simulation_run_configs")
    op.drop_index(op.f("ix_sim_agent_run_logs_simulation_run_id"), table_name="sim_agent_run_logs")
    op.drop_index(op.f("ix_sim_agent_run_logs_agent_instance_id"), table_name="sim_agent_run_logs")
    op.drop_index("idx_sim_agent_run_logs_run_id", table_name="sim_agent_run_logs")
    op.drop_index("idx_sim_agent_run_logs_instance_restart", table_name="sim_agent_run_logs")
    op.drop_table("sim_agent_run_logs")
    # ### end Alembic commands ###
