"""Make community_server_id nullable in requests table for backward compatibility

Revision ID: acdfba44673a
Revises: 76e7a7cc7edf
Create Date: 2025-11-18 17:50:44.342845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acdfba44673a"
down_revision: str | Sequence[str] | None = "76e7a7cc7edf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "community_server_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("requests_community_server_id_fkey"), "requests", type_="foreignkey")
    op.create_foreign_key(
        None, "requests", "community_servers", ["community_server_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("requests_community_server_id_fkey"),
        "requests",
        "community_servers",
        ["community_server_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column("requests", "community_server_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
