"""task-509: add is_opennotes_admin field to user_profiles

Revision ID: b71da3475e5d
Revises: task_508_add_cost_tracking
Create Date: 2025-11-07 15:58:01.453612

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b71da3475e5d"
down_revision: str | Sequence[str] | None = "task_508_add_cost_tracking"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column("is_opennotes_admin", sa.Boolean(), server_default="0", nullable=False),
    )
    op.create_index(
        "idx_user_profiles_is_opennotes_admin",
        "user_profiles",
        ["is_opennotes_admin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_profiles_is_opennotes_admin"),
        "user_profiles",
        ["is_opennotes_admin"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_is_opennotes_admin"), table_name="user_profiles")
    op.drop_index("idx_user_profiles_is_opennotes_admin", table_name="user_profiles")
    op.drop_column("user_profiles", "is_opennotes_admin")
    # ### end Alembic commands ###
