"""add_seen_request_ids_to_sim_agent_memory

Revision ID: b9a4ff797dca
Revises: 48fac3019407
Create Date: 2026-03-18 20:06:56.317337

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9a4ff797dca"
down_revision: str | Sequence[str] | None = "48fac3019407"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sim_agent_memories",
        sa.Column(
            "seen_request_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sim_agent_memories", "seen_request_ids")
    # ### end Alembic commands ###
