"""task-1123.01: add server_stats jsonb column to community_servers

Revision ID: bf30f9abfc03
Revises: c93bf6796c44
Create Date: 2026-02-17 14:43:45.918769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf30f9abfc03"
down_revision: str | Sequence[str] | None = "c93bf6796c44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "community_servers",
        sa.Column("server_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("community_servers", "server_stats")
    # ### end Alembic commands ###
