"""task-1144: add token bucket tables

Revision ID: c83119a1f5aa
Revises: 8a2a91a60527
Create Date: 2026-02-23 16:45:59.846965

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c83119a1f5aa"
down_revision: str | Sequence[str] | None = "8a2a91a60527"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_pools",
        sa.Column("pool_name", sa.String(length=128), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("pool_name"),
    )
    op.create_table(
        "token_holds",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("pool_name", sa.String(length=128), nullable=False),
        sa.Column("workflow_id", sa.String(length=256), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pool_name"],
            ["token_pools.pool_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pool_name", "workflow_id", name="uq_token_hold_pool_workflow"),
    )
    op.create_index(op.f("ix_token_holds_id"), "token_holds", ["id"], unique=False)
    op.create_index(op.f("ix_token_holds_pool_name"), "token_holds", ["pool_name"], unique=False)
    op.create_index(
        op.f("ix_token_holds_workflow_id"), "token_holds", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_holds_workflow_id"), table_name="token_holds")
    op.drop_index(op.f("ix_token_holds_pool_name"), table_name="token_holds")
    op.drop_index(op.f("ix_token_holds_id"), table_name="token_holds")
    op.drop_table("token_holds")
    op.drop_table("token_pools")
    # ### end Alembic commands ###
