"""task-1004.01: add rating_details column

Revision ID: c91286f2c37a
Revises: 5584986dda58
Create Date: 2026-01-14 18:32:52.903152

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c91286f2c37a"
down_revision: str | Sequence[str] | None = "5584986dda58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fact_check_items", sa.Column("rating_details", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "fact_checked_item_candidates",
        sa.Column("rating_details", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fact_checked_item_candidates", "rating_details")
    op.drop_column("fact_check_items", "rating_details")
    # ### end Alembic commands ###
