"""task-1123: add name column to monitored_channels

Revision ID: c93bf6796c44
Revises: 992453458994
Create Date: 2026-02-16 19:48:50.543488

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c93bf6796c44"
down_revision: str | Sequence[str] | None = "992453458994"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("monitored_channels", sa.Column("name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitored_channels", "name")
    # ### end Alembic commands ###
