"""Add image_description field to message_archive

Revision ID: d084f7c9e523
Revises: b8d9a79a333d
Create Date: 2025-11-04 10:02:37.281911

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d084f7c9e523"
down_revision: str | Sequence[str] | None = "b8d9a79a333d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.add_column("message_archive", sa.Column("image_description", sa.Text(), nullable=True))
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 20:56:42.951794+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 20:56:42.951794+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.drop_column("message_archive", "image_description")
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 20:56:42.951794+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-03 20:56:42.951794+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
