"""fix_timestamp_default_drift_fact_check_and_channels

Revision ID: d16b1a440fa7
Revises: 380416c4ea14
Create Date: 2025-11-04 11:10:09.627843

"""

from collections.abc import Sequence

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d16b1a440fa7"
down_revision: str | Sequence[str] | None = "380416c4ea14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Revert to removing the explicit NOW() defaults
    # The models will manage timestamp defaults at application level
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
