"""Add notes, ratings, and requests tables

Revision ID: d43c9fafe75d
Revises:
Create Date: 2025-10-20 13:59:18.686061

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d43c9fafe75d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "interactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interaction_id", sa.String(length=50), nullable=False),
        sa.Column("interaction_type", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.String(length=50), nullable=True),
        sa.Column("channel_id", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("command_name", sa.String(length=100), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("response_sent", sa.Boolean(), nullable=False),
        sa.Column("response_type", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interactions_created_at"), "interactions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_interactions_guild_id"), "interactions", ["guild_id"], unique=False)
    op.create_index(op.f("ix_interactions_id"), "interactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_interactions_interaction_id"), "interactions", ["interaction_id"], unique=True
    )
    op.create_index(op.f("ix_interactions_user_id"), "interactions", ["user_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.BigInteger(), nullable=False),
        sa.Column("author_participant_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tweet_id", sa.BigInteger(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "NOT_MISLEADING",
                "MISINFORMED_OR_POTENTIALLY_MISLEADING",
                name="note_classification",
            ),
            nullable=False,
        ),
        sa.Column("helpfulness_score", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEEDS_MORE_RATINGS",
                "CURRENTLY_RATED_HELPFUL",
                "CURRENTLY_RATED_NOT_HELPFUL",
                name="note_status",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notes_author_status", "notes", ["author_participant_id", "status"], unique=False
    )
    op.create_index("idx_notes_created_at", "notes", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_notes_author_participant_id"), "notes", ["author_participant_id"], unique=False
    )
    op.create_index(op.f("ix_notes_id"), "notes", ["id"], unique=False)
    op.create_index(op.f("ix_notes_note_id"), "notes", ["note_id"], unique=True)
    op.create_index(op.f("ix_notes_tweet_id"), "notes", ["tweet_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=50), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("discord_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("secret", sa.String(length=100), nullable=False),
        sa.Column("guild_id", sa.String(length=50), nullable=False),
        sa.Column("channel_id", sa.String(length=50), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_guild_id"), "webhooks", ["guild_id"], unique=False)
    op.create_index(op.f("ix_webhooks_id"), "webhooks", ["id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rater_participant_id", sa.String(length=255), nullable=False),
        sa.Column("note_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "helpfulness_level",
            sa.Enum("HELPFUL", "SOMEWHAT_HELPFUL", "NOT_HELPFUL", name="helpfulness_level"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.note_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ratings_created_at", "ratings", ["created_at"], unique=False)
    op.create_index(
        "idx_ratings_note_rater", "ratings", ["note_id", "rater_participant_id"], unique=True
    )
    op.create_index(op.f("ix_ratings_id"), "ratings", ["id"], unique=False)
    op.create_index(
        op.f("ix_ratings_rater_participant_id"), "ratings", ["rater_participant_id"], unique=False
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("tweet_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="request_status"),
            nullable=False,
        ),
        sa.Column("note_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.note_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_requests_requested_at", "requests", ["requested_at"], unique=False)
    op.create_index("idx_requests_status", "requests", ["status"], unique=False)
    op.create_index("idx_requests_tweet_status", "requests", ["tweet_id", "status"], unique=False)
    op.create_index(op.f("ix_requests_id"), "requests", ["id"], unique=False)
    op.create_index(op.f("ix_requests_request_id"), "requests", ["request_id"], unique=True)
    op.create_index(op.f("ix_requests_tweet_id"), "requests", ["tweet_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requests_tweet_id"), table_name="requests")
    op.drop_index(op.f("ix_requests_request_id"), table_name="requests")
    op.drop_index(op.f("ix_requests_id"), table_name="requests")
    op.drop_index("idx_requests_tweet_status", table_name="requests")
    op.drop_index("idx_requests_status", table_name="requests")
    op.drop_index("idx_requests_requested_at", table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_ratings_rater_participant_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_id"), table_name="ratings")
    op.drop_index("idx_ratings_note_rater", table_name="ratings")
    op.drop_index("idx_ratings_created_at", table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_webhooks_id"), table_name="webhooks")
    op.drop_index(op.f("ix_webhooks_guild_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_notes_tweet_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_note_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_author_participant_id"), table_name="notes")
    op.drop_index("idx_notes_created_at", table_name="notes")
    op.drop_index("idx_notes_author_status", table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_interactions_user_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_interaction_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_guild_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_created_at"), table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
