"""task_287_add_community_server_is_public_and_fk

Revision ID: dd5369cf2006
Revises: 3141f92c4208
Create Date: 2025-11-01 16:07:17.377635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd5369cf2006"
down_revision: str | Sequence[str] | None = "3141f92c4208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_public column to community_servers table (if not exists)
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='community_servers' AND column_name='is_public'"
        )
    )
    if not result.fetchone():
        op.add_column(
            "community_servers",
            sa.Column("is_public", sa.Boolean(), server_default="1", nullable=False),
        )
        op.create_index(
            "idx_community_servers_is_public", "community_servers", ["is_public"], unique=False
        )

    # Add foreign key constraint from community_members.community_id to community_servers.id (if not exists)
    result = conn.execute(
        sa.text(
            "SELECT constraint_name FROM information_schema.table_constraints "
            "WHERE table_name='community_members' AND constraint_name='fk_community_members_community_id'"
        )
    )
    if not result.fetchone():
        op.create_foreign_key(
            "fk_community_members_community_id",
            "community_members",
            "community_servers",
            ["community_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default="NOW()",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove foreign key constraint from community_members
    op.drop_constraint("fk_community_members_community_id", "community_members", type_="foreignkey")

    # Remove is_public column and index from community_servers
    op.drop_index("idx_community_servers_is_public", table_name="community_servers")
    op.drop_column("community_servers", "is_public")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "monitored_channels",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-01 23:06:06.888835+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "monitored_channels",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-01 23:06:06.888835+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-01 23:06:06.888835+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    op.alter_column(
        "fact_check_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("'2025-11-01 23:06:06.888835+00'::timestamp with time zone"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
