"""add_workflow_id_to_batch_jobs

Revision ID: eaa66fa1a5b4
Revises: 34353952be97
Create Date: 2026-01-28 12:40:30.049482

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eaa66fa1a5b4"
down_revision: str | Sequence[str] | None = "34353952be97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_jobs', sa.Column('workflow_id', sa.String(length=255), nullable=True, comment='DBOS workflow ID for workflow-backed jobs'))
    op.create_index(op.f('ix_batch_jobs_workflow_id'), 'batch_jobs', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_jobs_workflow_id'), table_name='batch_jobs')
    op.drop_column('batch_jobs', 'workflow_id')
    # ### end Alembic commands ###
