"""task-1124: add deleted_at to notes and requests

Revision ID: eadab3e9cb89
Revises: 992453458994
Create Date: 2026-02-16 18:11:57.801685

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eadab3e9cb89"
down_revision: str | Sequence[str] | None = "992453458994"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("idx_notes_deleted_at", "notes", ["deleted_at"], unique=False)
    op.add_column("requests", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("idx_requests_deleted_at", "requests", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_requests_deleted_at", table_name="requests")
    op.drop_column("requests", "deleted_at")
    op.drop_index("idx_notes_deleted_at", table_name="notes")
    op.drop_column("notes", "deleted_at")
    # ### end Alembic commands ###
