"""task-1238: add scopes column to api_keys

Revision ID: f591db73272e
Revises: 03f349b8269f
Create Date: 2026-03-06 16:13:13.534565

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f591db73272e"
down_revision: str | Sequence[str] | None = "03f349b8269f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys", sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "scopes")
    # ### end Alembic commands ###
