export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@opennotes/shared-types$': '<rootDir>/packages/shared-types/src/index.ts',
    '^@opennotes/shared-types/(.*)$': '<rootDir>/packages/shared-types/src/$1.ts',
    '^@opennotes/test-utils$': '<rootDir>/packages/test-utils/src/index.ts',
    '^@opennotes/test-utils/(.*)$': '<rootDir>/packages/test-utils/src/$1.ts',
  },
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: {
          target: 'ES2022',
          module: 'es2022',
          lib: ['ES2022'],
          moduleResolution: 'node',
          baseUrl: '.',
          rootDir: '.',
          paths: {
            '@opennotes/shared-types': ['./packages/shared-types/src/index.ts'],
            '@opennotes/shared-types/*': ['./packages/shared-types/src/*.ts'],
            '@opennotes/test-utils': ['./packages/test-utils/src/index.ts'],
            '@opennotes/test-utils/*': ['./packages/test-utils/src/*.ts'],
          },
          strict: true,
          useUnknownInCatchVariables: false,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          declaration: true,
          declarationMap: true,
          sourceMap: true,
          noUnusedLocals: false,
          noUnusedParameters: false,
          noImplicitReturns: true,
          noFallthroughCasesInSwitch: true,
        },
      },
    ],
  },
  testMatch: [
    '**/tests/**/*.test.ts',
  ],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/index.ts',
    '!src/logger.ts',
    '!src/config.ts',
    '!src/cache.ts',
    '!src/rate-limiter.ts',
    '!src/lib/discord-api.ts',
    '!src/functions/webhook.ts',
    '!src/commands/request-note.ts',
    '!src/commands/view-notes.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  // Coverage thresholds temporarily disabled - address in separate task
  // coverageThreshold: {
  //   global: {
  //     branches: 45,
  //     functions: 60,
  //     lines: 55,
  //     statements: 55,
  //   },
  // },
  testTimeout: 10000,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
};
